### ISSUE TITLE
Fails on Java 10 due to outdated AWS SDK version

### ISSUE THREAD

**Issue by ryan-richt** [frugalmechanic/fm-sbt-s3-resolver#52]
This SBT plugin is awesome thank you!

Unfortunately, it does not work on Java 10: `java version "10.0.2" 2018-07-17` (the default Homebrew version now) because you need a version of the AWS SDK newer than April 23rd of 2018 (per issue here: https://github.com/aws/aws-sdk-java/issues/1428) to work with newer versions of Java, lest you get the dreaded `[error] (common / publish) java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException` from the AWS SDK s3 client.

This project is currently at `val amazonSDKVersion = "1.11.236"`

Changing this to the latest as of today is:

`val amazonSDKVersion = "1.11.416"`

However, that does not compile with the current special scalac inlining settings.  Also removing: 
```
else Nil) ++ (if (scalaVersion.value.startsWith("2.12")) Seq(
  // Scala 2.12 specific compiler flags
  "-opt:l:inline",
  "-opt-inline-from:<sources>",
)
```
from build.sbt results in an artifact which I can confirms works all the way through to publish projects from sbt from a project that plugin-depends on this project, on a machine running Java 10, without Jaxb error.

Is it an acceptable solution to lose those settings @tpunder ?

Thank you,
ry

**Comment by tpunder** [comment]
@ryan-richt Sure sounds good to me. Changed made and published as version `0.17.0`.

Disabling the scalac optimizer settings shouldn't matter for this project.  Scala 2.12.7 (which is due any day now) will hopefully fix the optimizer issues on Java 9+.
